// <auto-generated />
using System;
using GhabzeTo.Infra.Data.EF.Uow;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeedMarket.Migrations
{
    [DbContext(typeof(EfUnitOfWork))]
    [Migration("20190227141303_SqlScriptForElmah")]
    partial class SqlScriptForElmah
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MeedMarket.EShop.GheymatKala", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Gheymat");

                    b.Property<Guid>("KalaId");

                    b.Property<long>("TolidKonandehId");

                    b.HasKey("Id");

                    b.HasIndex("KalaId");

                    b.HasIndex("TolidKonandehId");

                    b.ToTable("GheymatKalas");
                });

            modelBuilder.Entity("MeedMarket.EShop.Kala", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image");

                    b.Property<long>("KalaGroupId");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("Tozihat");

                    b.HasKey("Id");

                    b.HasIndex("KalaGroupId");

                    b.ToTable("Kalas");
                });

            modelBuilder.Entity("MeedMarket.EShop.KalaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileName");

                    b.Property<int>("KalaFileType");

                    b.Property<Guid>("KalaId");

                    b.Property<string>("Onvan");

                    b.HasKey("Id");

                    b.HasIndex("KalaId");

                    b.ToTable("KalaFiles");
                });

            modelBuilder.Entity("MeedMarket.EShop.KalaGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icon");

                    b.Property<long?>("ParentId");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("KalaGroups");
                });

            modelBuilder.Entity("MeedMarket.EShop.KalaVendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("KalaId");

                    b.Property<string>("TozieBarghCode");

                    b.Property<long>("TozieBarghId");

                    b.HasKey("Id");

                    b.HasIndex("KalaId");

                    b.HasIndex("TozieBarghId");

                    b.ToTable("KalaVendors");
                });

            modelBuilder.Entity("MeedMarket.EShop.TolidKonandeh", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TolidKonandehes");
                });

            modelBuilder.Entity("MeedMarket.EShop.TozieBargh", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TozieBarghes");
                });

            modelBuilder.Entity("MeedMarket.EShop.GheymatKala", b =>
                {
                    b.HasOne("MeedMarket.EShop.Kala", "Kala")
                        .WithMany()
                        .HasForeignKey("KalaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MeedMarket.EShop.TolidKonandeh", "TolidKonandeh")
                        .WithMany()
                        .HasForeignKey("TolidKonandehId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MeedMarket.EShop.Kala", b =>
                {
                    b.HasOne("MeedMarket.EShop.KalaGroup", "KalaGroup")
                        .WithMany()
                        .HasForeignKey("KalaGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MeedMarket.EShop.KalaFile", b =>
                {
                    b.HasOne("MeedMarket.EShop.Kala", "Kala")
                        .WithMany()
                        .HasForeignKey("KalaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MeedMarket.EShop.KalaGroup", b =>
                {
                    b.HasOne("MeedMarket.EShop.KalaGroup", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MeedMarket.EShop.KalaVendor", b =>
                {
                    b.HasOne("MeedMarket.EShop.Kala", "Kala")
                        .WithMany()
                        .HasForeignKey("KalaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MeedMarket.EShop.TozieBargh", "TozieBargh")
                        .WithMany()
                        .HasForeignKey("TozieBarghId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
