using System;

namespace GhabzeTo.Application.DTOs
{
    public class GhabzeBarghOutPutDto
    {
        public string NameMoshtarak { set; get; }
        public string Neshani { set; get; }
        public ulong CodePosti { set; get; }
        public ulong Parvande { set; get; }
        public ulong Eshterak { set; get; }
        public string Shenasaei { set; get; }
        public uint TedadeKhanevar { set; get; }
        public string OnvanVaCodeTarefe { set; get; }
        public string NoeFaAliat { set; get; }
        public int BadaneKontor { set; get; }
        public int Faz { set; get; }
        public int Amper { set; get; }
        public DateTime TarikheNasb { set; get; }
        public ulong ArghameKontor { set; get; }
        public DateTime TarikheEnghezayeParvane { set; get; }
        public string NahveGharateKontor { set; get; }
        public DateTime SodooreSooratHesab { set; get; }
        public DateTime MorajeBadi { set; get; }
        public short MantagheBargh { set; get; }
        public string NeshaniMarkazeMantaghe { set; get; }
        public uint VahedeHavadas { set; get; }
        public uint PasokhGooeiSooratHesab { set; get; }
        public string ShomareHsab { set; get; }
        public string MahalePardakht { set; get; }
        public int SaleGozashte1 { set; get; }
        public int SaleGozashte2 { set; get; }
        public int SaleGozashte3 { set; get; }
        public int SaleGozashte4 { set; get; }
        public int SaleGozashte5 { set; get; }
        public int SaleGozashte6 { set; get; }
        public int SaleJari1 { set; get; }
        public int SaleJari2 { set; get; }
        public int SaleJari3 { set; get; }
        public int SaleJari4 { set; get; }
        public int SaleJari5 { set; get; }
        public int SaleJari6 { set; get; }
        public string VaziatPardakht { set; get; }
        public DateTime TarikheGharateKonooni { set; get; }
        public uint MianBariKonooni { set; get; }
        public uint OjeBariKonooni { set; get; }
        public uint KamBariKonooni { set; get; }
        public string DoreKonooni { set; get; }
        public DateTime TarikheGharatePishin { set; get; }
        public uint MianBariGharatPishin { set; get; }
        public uint OjeBariGharatPishin { set; get; }
        public uint KamBariGharatPishin { set; get; }
        public uint MasrafeMianBari { set; get; }
        public uint MasrafeOjeBari { set; get; }
        public uint MasrafeKamBari { set; get; }
        public uint MasrafeKoleDore { set; get; }
        public uint MotevasateMasrafe30Rooze { set; get; }
        public uint TedadeRoozeDore { set; get; }
        public uint Masraf { set; get; }
        public uint Nerkh_0_100 { set; get; }
        public uint Masrafe30Rooze_0_100 { set; get; }
        public decimal Mablaghe_0_100 { set; get; }
        public decimal Nerkh_100_200 { set; get; }
        public decimal Masrafe30Rooze_100_200 { set; get; }
        public decimal Mablaghe_100_200 { set; get; }
        public decimal Nerkh_200_300 { set; get; }
        public decimal Masrafe30Rooze_200_300 { set; get; }
        public decimal Mablaghe_200_300 { set; get; }
        public decimal Nerkh_300_400 { set; get; }
        public decimal Masrafe30Rooze_300_400 { set; get; }
        public decimal Mablaghe_300_400 { set; get; }
        public decimal Nerkh_400_500 { set; get; }
        public decimal Masrafe30Rooze_400_500 { set; get; }
        public decimal Mablaghe_400_500 { set; get; }
        public decimal Nerkh_500_600 { set; get; }
        public decimal Masrafe30Rooze_500_600 { set; get; }
        public decimal Mablaghe_500_600 { set; get; }
        public decimal NerkhMazad600 { set; get; }
        public decimal Masrafe30RoozeMazad600 { set; get; }
        public decimal MablagheMazad600 { set; get; }
        public decimal MablagheMasraf { set; get; }
        public decimal EzafeHazineMasrafeOjeBar { set; get; }
        public decimal TakhfifeMasrafeKamBari { set; get; }
        public ulong ShenasePardakht { set; get; }
        public ulong ShenaseGhabz { set; get; }
        public DateTime MohlatePardakht { set; get; }
        public decimal HazineOjeBar { set; get; }
        public decimal TakhfifeKamBari { set; get; }
        public decimal AvarezeBargh { set; get; }
        public decimal Abonman { set; get; }
        public decimal PikeFasli { set; get; }
        public decimal BimeVahedHayeTejari { set; get; }
        public decimal MablagheDore { set; get; }
        public decimal MaliatBarArzesheAfzoode { set; get; }
        public decimal BedehiGhabli { set; get; }
        public decimal KasreRiali { set; get; }
        public decimal MablagheGhabelePardakht { set; get; }
        public string VaziatMasraf { set; get; }
    }
}
